[package]
name = "memsecurity"
version = "1.2.0"
authors = ["448 ENGINEERING DESIGN DEVELOPERS <superuser@448.africa>"]
license = "Apache-2.0 OR MIT"
description = "Securely hold secrets in memory and protect them against cross-protection-boundary readout via microarchitectural, via attacks on physical layout, and via coldboot attacks."
keywords = ["in-memory", "security"]
categories = ["cryptography", "memory-management"]
edition = "2021"
readme = "README.md"
homepage = "https://github.com/448-engineering/MEMSECURITY"
repository = "https://github.com/448-engineering/MEMSECURITY"

[badges]
maintenance = { status = "passively-maintained" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aead = { version = "0.5.2", features = ["bytes"], optional = true }
blake3 = { version = "1.3.3", default-features = false }
bytes = { version = "1.4.0" }
chacha20poly1305 = { version = "0.10.1", features = [
    "reduced-round",
], default-features = true, optional = true }
lazy_static = { version = "1.4.0", optional = true }
nanorand = { version = "0.7.0", features = [
    "chacha",
    "zeroize",
    "getrandom",
], optional = true }
zeroize = { version = "1.5.7", default-features = false }

[features]
default = []
encryption = ["dep:aead", "dep:chacha20poly1305", "dep:lazy_static", "random"]
random = ["dep:nanorand"]


[profile.dev]
overflow-checks = true

[profile.release]
opt-level = 3
strip = "debuginfo"
overflow-checks = true
lto = "thin"
